styleguide: plataformatec/linters
engines:
  credo:
    enabled: true
  fixme:
    enabled: true
  eslint:
    enabled: true
  remark-lint:
    enabled: true
exclude_paths:
  - config
  - test
  - assets/node_modules

